language: python
python:
  - "2.7"
  - "3.6"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
services:
 - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
 - psql -c 'create database pgdb;' -U postgres
 - psql -d pgdb -c "CREATE EXTENSION postgis;" -U postgres
script:
 - py.test
 - coverage run --source=pgdb -m py.test
after_success:
 - coveralls
sudo: false
