language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
services:
 - postgresql
addons:
  postgresql: 10.1
  apt:
    packages:
    - postgresql-10.1-postgis-2.4
    - gdal-bin
before_script:
 - psql -c 'create database pgdb;' -U postgres
 - psql -d pgdb -c "CREATE EXTENSION postgis;" -U postgres
script:
 - py.test
 - coverage run --source=pgdb -m py.test
after_success:
 - coveralls
sudo: false
