language: python
python:
  - "2.7"
  - "3.6"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
services:
  - postgresql
before_script:
  - psql -c 'create database pgdb;' -U postgres
script:
  - py.test
  - coverage run --source=pgdb -m py.test
after_success:
  - coveralls
sudo: false
