language: python
python:
  - "2.7"
  - "3.6"
env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
  matrix:
    - GDALVERSION="2.1.1"
install:
  - "pip install coveralls"
   - "if [ $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
  - "pip install --upgrade --force-reinstall --global-option=build_ext --global-option='-I$GDALINST/gdal-$GDALVERSION/include' --global-option='-L$GDALINST/gdal-$GDALVERSION/lib' --global-option='-R$GDALINST/gdal-$GDALVERSION/lib' -e ."
  - "pip install -e .[test]"
addons:
  apt:
    packages:
    - gdal-bin
services:
  - postgresql
before_install:
  - . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - gdal-config --version
before_script:
  - psql -c 'create database pgdb;' -U postgres
script:
  - py.test
  - coverage run --source=pgdb -m py.test
after_success:
  - coveralls
sudo: false
